name: Android Library CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Run tests
      run: ./gradlew test --stacktrace
    
    - name: Run lint
      run: ./gradlew lint --stacktrace
    
    - name: Build AAR (Release)
      run: ./gradlew assembleRelease --stacktrace
    
    - name: Generate Javadoc
      run: ./gradlew dokkaHtml
      continue-on-error: true
    
    - name: Upload AAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: library-aar
        path: '**/build/outputs/aar/*.aar'
        retention-days: 30
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/build/test-results/**/*.xml'
        retention-days: 30
    
    - name: Upload lint reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: lint-reports
        path: '**/build/reports/lint-results-*.html'
        retention-days: 30
    
    - name: Publish test report
      uses: mikepenz/action-junit-report@v4
      if: always()
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
        check_name: Test Results
        include_passed: true

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Publish to Maven Local (example)
      run: ./gradlew publishToMavenLocal
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
    
    # Descomente para publicar no GitHub Packages
    # - name: Publish to GitHub Packages
    #   run: ./gradlew publish
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    # Descomente para publicar no Maven Central
    # - name: Publish to Maven Central
    #   run: ./gradlew publishReleasePublicationToSonatypeRepository
    #   env:
    #     OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
    #     OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
    #     SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
    #     SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
    #     SIGNING_SECRET_KEY: ${{ secrets.SIGNING_SECRET_KEY }}
